### ISSUE TITLE
Choose colors for navbar links

### ISSUE THREAD

**Issue by ghost** [tylerpalmgren/tylerpalmgren.github.io#11]
Choose colors for navbar links in colors.css for links on dark navbar for a:hover, a:active, and li.active a.

**Comment by tylerpalmgren** [comment]
what is the issue? just to merge it?

**Comment by tylerpalmgren** [comment]
I'll do this tonight

**Comment by tylerpalmgren** [comment]
@NicholasHarang , I think just an easy combo could just be the same color as the background. Since the text is so small, it'll look darker than the background. Another combo could just be the cream color with the white color we were planning on using against the dark background. If it's legible enough on various brightnesses, then go with that.

**Comment by tylerpalmgren** [comment]
dark: #373737
cream:#DCD0C0
white:  #F4F4F4

**Comment by ghost** [comment]
Hopefully resolved by pull request #22

**Comment by ghost** [comment]
@tylerpalmgren can we close this?
